<!doctype html><html lang=en><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge,chrome=1"><title>Golang语法基础11-错误处理 | Shuzang&#39;s Blog</title><meta name=viewport content="width=device-width,initial-scale=1"><meta name=robots content="noodp"><meta name=Description content="shuzang's personal blog"><link rel=prev href=https://shuzang.github.io/2019/12/linux%E7%B3%BB%E7%BB%9F%E6%97%B6%E9%97%B4%E5%90%8C%E6%AD%A5/><link rel=next href=https://shuzang.github.io/2019/12/golang%E8%AF%AD%E6%B3%95%E5%9F%BA%E7%A1%8012-%E6%B5%8B%E8%AF%95/><link rel=canonical href=https://shuzang.github.io/2019/12/golang%E8%AF%AD%E6%B3%95%E5%9F%BA%E7%A1%8011-%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86/><link rel="shortcut icon" type=image/x-icon href=/favicon.ico><link rel=apple-touch-icon sizes=180x180 href=/apple-touch-icon.png><link rel=icon type=image/png sizes=32x32 href=/favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=/favicon-16x16.png><link rel=manifest href=/site.webmanifest><link rel=mask-icon href=/safari-pinned-tab.svg color=#5bbad5><meta name=msapplication-TileColor content="#da532c"><meta name=theme-color content="#ffffff"><meta name=twitter:card content="summary"><meta name=twitter:title content="Golang语法基础11-错误处理"><meta name=twitter:description content="Go中有两套错误处理的方式 普通错误： 在函数和方法中返回错误对象作为它们的唯一或最后一个返回值 ，如果返回nil，表示没有错误 异常：使用pani"><script type=application/ld+json>{"@context":"http://schema.org","@type":"BlogPosting","headline":"Golang语法基础11-错误处理","mainEntityOfPage":{"@type":"WebPage","@id":"https:\/\/shuzang.github.io\/2019\/12\/golang%E8%AF%AD%E6%B3%95%E5%9F%BA%E7%A1%8011-%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86\/"},"image":{"@type":"ImageObject","url":"https:\/\/shuzang.github.io\/cover.png","width":800,"height":600},"genre":"posts","keywords":"Golang","wordcount":2636,"url":"https:\/\/shuzang.github.io\/2019\/12\/golang%E8%AF%AD%E6%B3%95%E5%9F%BA%E7%A1%8011-%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86\/","datePublished":"2019-12-20T00:00:00\x2b00:00","dateModified":"2019-12-20T00:00:00\x2b00:00","license":"This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.","publisher":{"@type":"Organization","name":"shuzang","logo":{"@type":"ImageObject","url":"https:\/\/shuzang.github.io\/logo.png","width":127,"height":40}},"description":""}</script><link rel=stylesheet href=/css/style.min.css><link rel=stylesheet href=/css/lib/fontawesome-free/all.min.css><link rel=stylesheet href=/css/lib/animate/animate.min.css></head><body><script>window.isDark=(window.localStorage&&window.localStorage.getItem('theme'))==='dark';window.isDark&&document.body.classList.add('dark-theme');</script><div class=wrapper><nav class=navbar><div class=navbar-container><div class="navbar-header animated bounceIn"><a href=https://shuzang.github.io>Shuzang&#39;s Blog</a></div><div class=navbar-menu><a class=menu-item href=https://shuzang.github.io/posts>Posts</a><a class=menu-item href=https://shuzang.github.io/categories>Categories</a><a class=menu-item href=https://shuzang.github.io/tags>Tags</a><a class=menu-item href=https://shuzang.github.io/life>Life</a><a class=menu-item href=https://shuzang.github.io/about>About</a><a href=javascript:void(0); class=theme-switch><i class="fas fa-adjust fa-rotate-180 fa-fw" title="Switch Theme"></i></a></div></div></nav><nav class=navbar-mobile><div class=navbar-container><div class=navbar-header><div class="navbar-header-title animated bounceIn"><a href=https://shuzang.github.io>Shuzang&#39;s Blog</a></div><div class=menu-toggle id=menu-toggle><span></span><span></span><span></span></div></div><div class=navbar-menu id=mobile-menu><a class=menu-item href=https://shuzang.github.io/posts>Posts</a><a class=menu-item href=https://shuzang.github.io/categories>Categories</a><a class=menu-item href=https://shuzang.github.io/tags>Tags</a><a class=menu-item href=https://shuzang.github.io/life>Life</a><a class=menu-item href=https://shuzang.github.io/about>About</a><a href=javascript:void(0); class=theme-switch><i class="fas fa-adjust fa-rotate-180 fa-fw" title="Switch Theme"></i></a></div></div></nav><main class=main><div class=container><article class=page><h1 class="post-title animated flipInX">Golang语法基础11-错误处理</h1><div class=post-meta><div class=post-meta-main><a class=author href=https://shuzang.github.io rel=author target=_blank><i class="fas fa-user-circle fa-fw"></i>shuzang
</a>&nbsp;<span class=post-category>included in&nbsp;<i class="far fa-folder fa-fw"></i><a href=https://shuzang.github.io/categories/%E7%88%B1%E7%BC%96%E7%A8%8B%E7%88%B1%E6%8A%80%E6%9C%AF%E7%9A%84%E5%AD%A9%E5%AD%90/>爱编程爱技术的孩子</a>&nbsp;</span></div><div class=post-meta-other><i class="far fa-calendar-alt fa-fw"></i><time datetime=2019-12-20>2019-12-20</time>&nbsp;
<i class="fas fa-pencil-alt fa-fw"></i>about 2636 words&nbsp;
<i class="far fa-clock fa-fw"></i>6 min&nbsp;</div></div><div class=post-toc id=post-toc><h2 class=post-toc-title>Contents</h2><div class=post-toc-content><nav id=TableOfContents><ul><li><ul><li><a href=#1-普通错误>1. 普通错误</a><ul><li><a href=#1-1-定义错误>1.1 定义错误</a></li><li><a href=#1-2-输出更多的错误信息>1.2 输出更多的错误信息</a></li></ul></li><li><a href=#2-异常>2. 异常</a><ul><li><a href=#2-1-panic>2.1 panic</a></li><li><a href=#2-2-panicking>2.2 panicking</a></li><li><a href=#2-3-recover>2.3 recover</a></li></ul></li><li><a href=#3-错误处理的一些原则>3. 错误处理的一些原则</a></li><li><a href=#4-闭包处理错误>4. 闭包处理错误</a></li></ul></li></ul></nav></div></div><div class=post-toc-mobile id=post-toc-mobile><details><summary><div class=post-toc-title><span>Contents</span>
<span><i class="details icon fas fa-angle-down"></i></span></div></summary><div class=post-toc-content><nav id=TableOfContentsMobile><ul><li><ul><li><a href=#1-普通错误>1. 普通错误</a><ul><li><a href=#1-1-定义错误>1.1 定义错误</a></li><li><a href=#1-2-输出更多的错误信息>1.2 输出更多的错误信息</a></li></ul></li><li><a href=#2-异常>2. 异常</a><ul><li><a href=#2-1-panic>2.1 panic</a></li><li><a href=#2-2-panicking>2.2 panicking</a></li><li><a href=#2-3-recover>2.3 recover</a></li></ul></li><li><a href=#3-错误处理的一些原则>3. 错误处理的一些原则</a></li><li><a href=#4-闭包处理错误>4. 闭包处理错误</a></li></ul></li></ul></nav></div></details></div><div class=post-content><p>Go中有两套错误处理的方式</p><ul><li>普通错误： 在函数和方法中返回错误对象作为它们的唯一或最后一个返回值 ，如果返回nil，表示没有错误</li><li>异常：使用panic和recover</li></ul><p>主调函数总是应该检查收到的错误，不要忽略，否则可能导致严重的后果。</p><a class=post-dummy-target id=1-普通错误></a><h2>1. 普通错误</h2><p>Go有一个预定义的error接口类型</p><pre><code class=language-go>type error interface {
    Error() string
}
</code></pre><p>errors包中有一个errorString结构体实现了该接口，</p><a class=post-dummy-target id=1-1-定义错误></a><h3>1.1 定义错误</h3><p>当我们需要一个新的错误类型，可以使用<code>errors</code>包的<code>errors.New</code>函数接收合适的信息来创建，如下例</p><pre><code class=language-go>err := errors.New(&quot;math - square root of negative number&quot;)
</code></pre><p>可以将其用于计算平方根函数的参数测试</p><pre><code class=language-go>func Sqrt(f float64) (float64, error) {
    if f &lt; 0 {
        return 0, errors.New(&quot;math - square root of negative number&quot;)
    }
    //implementation of Sqrt
}
</code></pre><p>然后像下面这样调用<code>Sqrt</code>函数</p><pre><code class=language-go>if f, err := Sqrt(-1); err != nil {
    fmt.Printf(&quot;Error: %s\n&quot;, err)
}
</code></pre><p>使用<code>fmt.Printf</code>将错误信息打印出来，定义的错误信息通过会有像<code>Error:</code>这样的前缀，所以错误信息的内容不要以大写字母开头，如上例中使用<code>math</code>而不是<code>Math</code></p><p>大部分情况自定义错误类型都是很有用的方法，可以将底层错误信息之外的其它有用信息打印出来。如果有不同的错误条件，就可以用类型断言判断错误场景，并做一些补救和恢复</p><pre><code class=language-go>switch err := err.(type) {
	case ParseError:
		PrintParseError(err)
	case PathError:
		PrintPathError(err)
	...
	default:
		fmt.Printf(&quot;Not a special error, just %s\n&quot;, err)
}
</code></pre><p>包也可以用额外的方法定义特定的错误，如net.Error:</p><pre><code class=language-go>package net
type Error interface {
	Timeout() bool   // Is the error a timeout?
	Temporary() bool // Is the error temporary?
}
</code></pre><p>如前所述，所有的例子都遵循同一种命名规范： 错误类型以 “Error” 结尾，错误变量以 “err” 或 “Err” 开头。</p><a class=post-dummy-target id=1-2-输出更多的错误信息></a><h3>1.2 输出更多的错误信息</h3><p><code>fmt.Errorf()</code>是一个常用的<code>fmt</code>包的函数，用于输出更多的错误信息，而不是单单一个字符串。如前面平方根的例子</p><pre><code class=language-go>if f &lt; 0 {
    return 0, fmt.Errorf(&quot;math: squre root of negative number %g&quot;, f)
}
</code></pre><p>所以可以得知，<code>fmt.Errorf</code>和<code>errors.New</code>都返回<code>error</code>类型的变量</p><a class=post-dummy-target id=2-异常></a><h2>2. 异常</h2><p>或者称为运行时异常，指的是那些无法预测的错误。比如数组下标越界或类型断言失败，就会触发异常，并且伴随着程序终止返回一个<code>runtime.Error</code>接口类型的值，这个值和普通错误的区别在于有一个<code>RuntimeError()</code>方法</p><a class=post-dummy-target id=2-1-panic></a><h3>2.1 panic</h3><p><code>panic</code>就是Go中用于生成异常的方法。当错误不可修复、程序无法继续运行时，使用<code>panic</code>函数来产生一个中止程序的运行时错误，<code>panic</code>接收任意类型的参数，通常是字符串，这个参数会在程序终止时被打印出来。中止程序和打印参数的过程由Go runtime负责。一个例子如下</p><pre><code class=language-go>package main

import &quot;fmt&quot;

func main() {
	fmt.Println(&quot;Starting the program&quot;)
	panic(&quot;A severe error occurred: stopping the program!&quot;)
	fmt.Println(&quot;Ending the program&quot;)
}
</code></pre><p>输出如下</p><pre><code class=language-go>Starting the program
panic: A severe error occurred: stopping the program!
panic PC=0x4f3038
runtime.panic+0x99 /go/src/pkg/runtime/proc.c:1032
       runtime.panic(0x442938, 0x4f08e8)
main.main+0xa5 E:/Go/GoBoek/code examples/chapter 13/panic.go:8
       main.main()
runtime.mainstart+0xf 386/asm.s:84
       runtime.mainstart()
runtime.goexit /go/src/pkg/runtime/proc.c:148
       runtime.goexit()
---- Error run E:/Go/GoBoek/code examples/chapter 13/panic.exe with code Crashed
---- Program exited with code -1073741783
</code></pre><p>一个检测到错误然后使用panic抛出异常的完整例子如下</p><pre><code class=language-go>if err != nil {
	panic(&quot;ERROR occurred:&quot; + err.Error())
}
</code></pre><p>但panic抛出异常并中止程序是最后的办法，如果有修复的可能就不应该使用</p><a class=post-dummy-target id=2-2-panicking></a><h3>2.2 panicking</h3><p>在多层嵌套的函数调用中使用panic，可以马上中止当前函数的执行，所有的defer语句都会保证执行并把控制权交还给接收到panic的函数调用者。这样向上冒泡直到最顶层，并执行（每层的）defer，在栈顶处程序崩溃，并在命令行中用传给panic的值报告错误情况：这个终止的过程就是panicking。</p><a class=post-dummy-target id=2-3-recover></a><h3>2.3 recover</h3><p><code>revocer</code>函数用于让程序从<code>panicking</code>重新获得控制权，停止终止过程进而恢复正常执行，但<code>recover</code>只能在<code>defer</code>修饰的函数中使用。如果正常执行，调用<code>recover</code>会返回nil，没有其它效果。</p><p>简而言之，panicking有两个结果，一个是程序终止，一个是遇到defer修饰的recover()函数然后恢复。一个例子如下</p><pre><code class=language-go>func protect(g func()) {
	defer func() {
		log.Println(&quot;done&quot;)
		// Println executes normally even if there is a panic
		if err := recover(); err != nil {
			log.Printf(&quot;run time panic: %v&quot;, err)
		}
	}()
	log.Println(&quot;start&quot;)
	g() //   possible runtime-error
}
</code></pre><p>将panic，defer和recover结合的完整例子如下</p><pre><code class=language-go>package main

import (
	&quot;fmt&quot;
)

func badCall() {
	panic(&quot;bad end&quot;)
}

func test() {
	defer func() {
		if e := recover(); e != nil {
			fmt.Printf(&quot;Panicing %s\r\n&quot;, e)
		}
	}()
	badCall()
	fmt.Printf(&quot;After bad call\r\n&quot;) // &lt;-- wordt niet bereikt
}

func main() {
	fmt.Printf(&quot;Calling test\r\n&quot;)
	test()
	fmt.Printf(&quot;Test completed\r\n&quot;)
}
</code></pre><p>输出</p><pre><code class=language-go>Calling test
Panicing bad end
Test completed
</code></pre><a class=post-dummy-target id=3-错误处理的一些原则></a><h2>3. 错误处理的一些原则</h2><p>这是在编写自己的包时需要遵循的一些原则，有助于别人调用和程序正常运行</p><ol><li>在包内部，总是在panic后使用recover，不要让panic返回的层次超出当前包的范围</li><li>向包的调用者返回错误值，而不是panic</li><li>在包内部的不可导出函数中有深层次调用时，将panic转换成error来通知调用者出错信息</li></ol><p>根据此原则，一个<code>parse</code>包如下，作用是把输入的字符串解析为整数切片</p><pre><code class=language-go>package parse

import (
	&quot;fmt&quot;
	&quot;strings&quot;
	&quot;strconv&quot;
)

// A ParseError indicates an error in converting a word into an integer.
type ParseError struct {
    Index int      // The index into the space-separated list of words.
    Word  string   // The word that generated the parse error.
    Err error // The raw error that precipitated this error, if any.
}

// String returns a human-readable error message.
func (e *ParseError) String() string {
    return fmt.Sprintf(&quot;pkg parse: error parsing %q as int&quot;, e.Word)
}

// Parse parses the space-separated words in in put as integers.
func Parse(input string) (numbers []int, err error) {
    defer func() {
        if r := recover(); r != nil {
            var ok bool
            err, ok = r.(error)
            if !ok {
                err = fmt.Errorf(&quot;pkg: %v&quot;, r)
            }
        }
    }()

    fields := strings.Fields(input)
    numbers = fields2numbers(fields)
    return
}

func fields2numbers(fields []string) (numbers []int) {
    if len(fields) == 0 {
        panic(&quot;no words to parse&quot;)
    }
    for idx, field := range fields {
        num, err := strconv.Atoi(field)
        if err != nil {
            panic(&amp;ParseError{idx, field, err})
        }
        numbers = append(numbers, num)
    }
    return
}
</code></pre><p>该包定义了自己的<code>ParseError</code>，当没有东西需要转换或转换成整数失败时，产生panic，但可导出的Parse函数会从panic中recover并整合信息返回一个错误给调用者。</p><p>一个调用parse包的实例如下</p><pre><code class=language-go>package main

import (
	&quot;fmt&quot;
	&quot;./parse/parse&quot;
)

func main() {
    var examples = []string{
            &quot;1 2 3 4 5&quot;,
            &quot;100 50 25 12.5 6.25&quot;,
            &quot;2 + 2 = 4&quot;,
            &quot;1st class&quot;,
            &quot;&quot;,
    }

    for _, ex := range examples {
        fmt.Printf(&quot;Parsing %q:\n  &quot;, ex)
        nums, err := parse.Parse(ex)
        if err != nil {
            fmt.Println(err) // here String() method from ParseError is used
            continue
        }
        fmt.Println(nums)
    }
}
</code></pre><p>输出</p><pre><code class=language-go>Parsing &quot;1 2 3 4 5&quot;:
  [1 2 3 4 5]
Parsing &quot;100 50 25 12.5 6.25&quot;:
  pkg: pkg parse: error parsing &quot;12.5&quot; as int
Parsing &quot;2 + 2 = 4&quot;:
  pkg: pkg parse: error parsing &quot;+&quot; as int
Parsing &quot;1st class&quot;:
  pkg: pkg parse: error parsing &quot;1st&quot; as int
Parsing &quot;&quot;:
  pkg: no words to parse
</code></pre><a class=post-dummy-target id=4-闭包处理错误></a><h2>4. 闭包处理错误</h2><p>根据上面的原则，只要有函数返回，就应该检查是否有错误发生，但这会导致重复乏味的代码。结合 defer/panic/recover 机制和闭包可以得到一种更加优雅的写法。不过这种写法的限制是所有函数都需要是同一种签名。</p><p>假设所有函数签名都是下面这种形式</p><pre><code class=language-go>func f(a type1, b type2)
</code></pre><p>参数的数量和类型是不相关的，我们给这个类型一个名字：</p><pre><code>fType1 = func f(a type1, b type2)
</code></pre><p>使用两个辅助函数帮忙完成整个过程</p><ol><li><p>check：用来检查是否有错误和panic发生的函数</p><pre><code class=language-go>func check(err error) { if err != nil { panic(err) } }
</code></pre></li><li><p>errorhandler：接收一个 fType1 类型的函数 fn 并返回一个调用 fn 的函数, 其中包含有 defer/recover 机制</p><pre><code class=language-go>func errorHandler(fn fType1) fType1 {
	return func(a type1, b type2) {
		defer func() {
			if err, ok := recover().(error); ok {
				log.Printf(&quot;run time panic: %v&quot;, err)
			}
		}()
		fn(a, b)
	}
}
</code></pre></li></ol><p>当错误发生时会 recover 并打印在日志中，check() 函数会在所有的被调函数中调用，像这样：</p><pre><code class=language-go>func f1(a type1, b type2) {
	...
	f, _, err := // call function/method
	check(err)
	t, err := // call function/method
	check(err)
	_, err2 := // call function/method
	check(err2)
	...
}
</code></pre><p>通过这种机制，所有的错误都会被 recover，并且调用函数后的错误检查代码也被简化为调用 check(err) 即可。在这种模式下，不同的错误处理必须对应不同的函数类型；它们（错误处理）可能被隐藏在错误处理包内部。可选的更加通用的方式是用一个空接口类型的切片作为参数和返回值。</p></div><div class=post-footer id=post-footer><div class=post-info><div class=post-info-line><div class=post-info-mod><span>The article was updated on 2019-12-20</span></div><div class=post-info-license></div></div><div class=post-info-line><div class=post-info-md></div><div class=post-info-share><span><a href="//twitter.com/share?url=https%3a%2f%2fshuzang.github.io%2f2019%2f12%2fgolang%25E8%25AF%25AD%25E6%25B3%2595%25E5%259F%25BA%25E7%25A1%258011-%25E9%2594%2599%25E8%25AF%25AF%25E5%25A4%2584%25E7%2590%2586%2f&amp;text=Golang%e8%af%ad%e6%b3%95%e5%9f%ba%e7%a1%8011-%e9%94%99%e8%af%af%e5%a4%84%e7%90%86&amp;via=" target=_blank title="Share on Twitter"><i class="fab fa-twitter fa-fw"></i></a><a href="//www.facebook.com/sharer/sharer.php?u=https%3a%2f%2fshuzang.github.io%2f2019%2f12%2fgolang%25E8%25AF%25AD%25E6%25B3%2595%25E5%259F%25BA%25E7%25A1%258011-%25E9%2594%2599%25E8%25AF%25AF%25E5%25A4%2584%25E7%2590%2586%2f" target=_blank title="Share on Facebook"><i class="fab fa-facebook-square fa-fw"></i></a><a href="//reddit.com/submit?url=https%3a%2f%2fshuzang.github.io%2f2019%2f12%2fgolang%25E8%25AF%25AD%25E6%25B3%2595%25E5%259F%25BA%25E7%25A1%258011-%25E9%2594%2599%25E8%25AF%25AF%25E5%25A4%2584%25E7%2590%2586%2f&amp;title=Golang%e8%af%ad%e6%b3%95%e5%9f%ba%e7%a1%8011-%e9%94%99%e8%af%af%e5%a4%84%e7%90%86" target=_blank title="Share on Reddit"><i class="fab fa-reddit fa-fw"></i></a></span></div></div></div><div class=post-info-more><section><span class=tag><a href=https://shuzang.github.io/tags/golang/><i class="fas fa-tag fa-fw"></i>&nbsp;Golang</a>&nbsp;</span></section><section><span><a href=javascript:window.history.back();>Back</a></span>&nbsp;|&nbsp;<span><a href=https://shuzang.github.io>Home</a></span></section></div><div class=post-nav><a href=https://shuzang.github.io/2019/12/linux%E7%B3%BB%E7%BB%9F%E6%97%B6%E9%97%B4%E5%90%8C%E6%AD%A5/ class=prev rel=prev title=linux系统时间同步><i class="fas fa-angle-left fa-fw"></i>linux系统时间同步</a>
<a href=https://shuzang.github.io/2019/12/golang%E8%AF%AD%E6%B3%95%E5%9F%BA%E7%A1%8012-%E6%B5%8B%E8%AF%95/ class=next rel=next title=Golang语法基础12-测试>Golang语法基础12-测试<i class="fas fa-angle-right fa-fw"></i></a></div></div><div class=post-comment></div></article></div></main><footer class=footer><div class=copyright><div class=copyright-line>Powered by <a href=https://gohugo.io/ target=_blank rel="external nofollow noopener noreffer">Hugo</a> | Theme - <a href=https://github.com/dillonzq/LoveIt target=_blank rel="external nofollow noopener noreffer">LoveIt<i class="far fa-heart fa-fw"></i></a></div><div class=copyright-line><i class="far fa-copyright fa-fw"></i><span itemprop=copyrightYear>2018 - 2020</span><span class=author itemprop=copyrightHolder>&nbsp;<a href=https://shuzang.github.io target=_blank>shuzang</a></span>&nbsp;|&nbsp;<span class=license><a rel="license external nofollow noopener noreffer" href=https://creativecommons.org/licenses/by-nc/4.0/ target=_blank>CC BY-NC 4.0</a></span></div></div></footer></div><a href=# class=dynamic-to-top id=dynamic-to-top data-scroll><span>&nbsp;</span>
</a><script src=/js/lib/jquery/jquery.slim.min.js></script><script src=/js/lib/lazysizes/lazysizes.min.js></script><script src=/js/lib/smooth-scroll/smooth-scroll.polyfills.min.js></script><script>window.scroll=new SmoothScroll('[data-scroll]',{speed:300,speedAsDuration:true});</script><link rel=stylesheet href=/css/lib/katex/katex.min.css><script src=/js/lib/katex/katex.min.js></script><script defer src=/js/lib/katex/auto-render.min.js></script><link rel=stylesheet href=/css/lib/katex/copy-tex.min.css><script defer src=/js/lib/katex/copy-tex.min.js></script><script defer src=/js/lib/katex/mhchem.min.js></script><script>document.addEventListener("DOMContentLoaded",function(){renderMathInElement(document.body,{delimiters:[{left:"$$",right:"$$",display:true},{left:"\\(",right:"\\)",display:false},{left:"\\[",right:"\\]",display:true},{left:"$",right:"$",display:false},]});});</script><script src=/js/blog.min.js></script></body></html>